apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: rubrik-kupr
  name: rubrik-kubeconfig-role
rules:
# Required to deploy the Rubrik backup agent, deploy the CRD controller and configure the load balancer service
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["create", "delete", "get", "update", "patch"]
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["create", "delete", "get"]
- apiGroups: [""]
  resources: ["secrets", "serviceaccounts", "services"]
  verbs: ["create", "get", "update", "patch"]

# Required to create sample Roles for CRD RBAC
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["roles"]
  verbs: ["create", "get", "update", "patch"]
