# ClusterRole with permissions required by the Rubrik Kubeconfig
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rubrik-kubeconfig-cluster-role
rules:
# Required to create the rubrik-kupr namespace and new namespaces during export and to delete the rubrik-kupr namespace when removing the cluster
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["delete"]
  resourceNames: ["rubrik-kupr"]

# Required to list namespaces in UI
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["list", "get"]

# Required to perform backup and recovery of PVCs
- apiGroups: ["snapshot.storage.k8s.io"]
  resources: ["volumesnapshotcontents", "volumesnapshots"] 
  verbs: ["create", "get", "list", "delete", "patch", "update"]
- apiGroups: ["snapshot.storage.k8s.io"]
  resources: ["volumesnapshotclasses"]
  verbs: ["list"]
- apiGroups: ["storage.k8s.io"]
  resources: ["storageclasses"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["persistentvolumes"]
  verbs: ["get", "patch", "update"]

# Required to manage Rubrik-owned CRDs
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  resourceNames: [
    "filters.apps.kupr.rubrik.com",
    "hooks.apps.kupr.rubrik.com",
    "protectionsets.apps.kupr.rubrik.com",
    "snapshots.apps.kupr.rubrik.com",
    "k8sclusters.clusters.kupr.rubrik.com",
    "rubrikclusters.clusters.kupr.rubrik.com",
    "recoveryjobs.jobs.kupr.rubrik.com",
    "snapshotjobs.jobs.kupr.rubrik.com",
    "sladomains.sla.kupr.rubrik.com",
  ]
  verbs: ["get", "delete", "patch", "update"]
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["create"]

# Required to keep the Rubrik CR objects in sync with RSC
- apiGroups: ["apps.kupr.rubrik.com"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["jobs.kupr.rubrik.com"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["clusters.kupr.rubrik.com"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["sla.kupr.rubrik.com"]
  resources: ["*"]
  verbs: ["*"]

# Required to create ClusterRoleBindings for the CRD controller
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["clusterroles"]
  verbs: ["get", "update"]
  resourceNames: ["kupr-user", "kupr-admin", "rubrik-kupr-appscontroller-role"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["clusterroles"]
  verbs: ["create"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["clusterrolebindings"]
  verbs: ["get", "update"]
  resourceNames: ["rubrik-kupr-appscontroller-rolebinding"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["clusterrolebindings"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "get", "list", "patch", "update", "watch"]

# This rule allows Rubrik to get/update only secrets with the name “rubrik-svcacnt” and allows creating new secrets.
# The “rubrik-svcacnt” secret is created in the rubrik-kupr namespace and is used to store the RSC service account. The Rubrik Controller needs this for Rubrik CRDs to function properly.
# This rule is only needed in the rubrik-kupr namespace but since the namespace doesn’t exist before adding the K8s cluster, it needs to be in the ClusterRole during cluster registration.
# Adding a K8s cluster will fail without this. This permission can be removed once the K8s cluster is added to RSC successfully.
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "update"]
  resourceNames: ["rubrik-svcacnt"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create"]

# Required to provide anyuid SCC permissions to rubrik-kupr service account
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["clusterrolebindings"]
  verbs: ["get", "update"]
  resourceNames: ["rubrik-kupr-anyuid-scc-rolebinding"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["clusterrolebindings"]
  verbs: ["create"]

# Required to run the Rubrik Backup Agent as root in rubrik-kupr namespace
- apiGroups: ["security.openshift.io"]
  resources: ["securitycontextconstraints"]
  resourceNames: ["anyuid"]
  verbs: ["use"]